<h1>Numpy</h1>

![Numpy.](https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/1920px-NumPy_logo_2020.svg.png)      

<a href="https://numpy.org/doc/stable/user/quickstart.html"><h3> NumPy quickstart </h3></a>    

<h1>Numpy: Its main object is a table of elements (usually numbers) </h1>

In [3]:
import numpy as np

<h4>Vector addition</h4>

$$\begin{bmatrix}
2 & 3 & 7 & 4 
\end{bmatrix} +
\begin{bmatrix}
0 & 1  & 5 &  -2
\end{bmatrix}
=
\begin{bmatrix}
 2& 4  & 12   & 2 
\end{bmatrix}
$$

In [22]:
ar_1 = np.array([2,3,7,4])
ar_2 = np.array([0,1,5,-2])
ar_1 + ar_2

array([ 2,  4, 12,  2])

<h4>Matrix addition </h4>

$$
\begin{bmatrix}
1 & 2 & 0 & 4 \\ 
5 & -1 & 7 & 0 \\ 
1 & 2  & 1  & -1 
\end{bmatrix}
+
\begin{bmatrix}
1 & 0 & 2 & 3 \\ 
2 & 1 & 3 & -1 \\ 
1.5 & 3 & 4  & -\pi
\end{bmatrix}
=
\begin{bmatrix}
2 & 2 & 2  & 7 \\ 
7 & 0  & 10  & -1 \\ 
2.5 & 5 & 5 & -\pi -1
\end{bmatrix}
$$

In [28]:
m1 = np.array([ [1,2,0,4] , [5,-1,7,0] , [1,2,1,-1] ])
m2 = np.array([ [1,0,2,3] , [2, 1,3,-1] , [1.5 ,3 , 4 ,-np.pi] ])
m1 + m2

array([[ 2.        ,  2.        ,  2.        ,  7.        ],
       [ 7.        ,  0.        , 10.        , -1.        ],
       [ 2.5       ,  5.        ,  5.        , -4.14159265]])

<h4>Matrix multiplication: Hadamard product or  element-wise product </h4>

$$
\begin{bmatrix}
1 & 2 & 0 & 4 \\ 
5 & -1 & 7 & 0 \\ 
1 & 2  & 1  & -1 
\end{bmatrix}
\circ
\begin{bmatrix}
1 & 0 & 2 & 3 \\ 
2 & 1 & 3 & -1 \\ 
1.5 & 3 & 4  & -\pi
\end{bmatrix}
=
\begin{bmatrix}
1 & 0 & 0  & 12 \\ 
10 & -1  & 21  & 0 \\ 
1.5 & 6 & 4 & -\pi 
\end{bmatrix}
$$

In [29]:
m1 * m2 

array([[ 1.        ,  0.        ,  0.        , 12.        ],
       [10.        , -1.        , 21.        , -0.        ],
       [ 1.5       ,  6.        ,  4.        ,  3.14159265]])

<h4>Matrix product</h4>

![Numpy.](https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Matrix_multiplication_diagram_2.svg/1024px-Matrix_multiplication_diagram_2.svg.png)      

In [46]:
A = np.array([[1 ,3 ], [2 , 0] ,[ 3, -1] ,[0,4] ])
B = np.array([[-1 ,2 ,3  ], [2 , -1 ,1 ]  ])
print(A)
print()
print(B)

[[ 1  3]
 [ 2  0]
 [ 3 -1]
 [ 0  4]]

[[-1  2  3]
 [ 2 -1  1]]


In [48]:
C = np.matmul(A , B)

In [49]:
C

array([[ 5, -1,  6],
       [-2,  4,  6],
       [-5,  7,  8],
       [ 8, -4,  4]])

In [53]:
np.diag(C , k=-2)

array([-5, -4])

In [57]:
np.flip(C ,axis = 0 )

array([[ 8, -4,  4],
       [-5,  7,  8],
       [-2,  4,  6],
       [ 5, -1,  6]])

In [58]:
C

array([[ 5, -1,  6],
       [-2,  4,  6],
       [-5,  7,  8],
       [ 8, -4,  4]])

In [59]:
ar_1

array([2, 3, 7, 4])

In [60]:
ar_2

array([ 0,  1,  5, -2])

In [63]:
np.stack([ar_1 , ar_2] ,axis=1)

array([[ 2,  0],
       [ 3,  1],
       [ 7,  5],
       [ 4, -2]])